SELECT SUM(HG.SCORE) SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_DEPARTMENT HD ON HD.DEPT_ID = HE.DEPT_ID
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1